<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Auth\Middleware\Authenticate as Middleware;
use App\Models\Permissions;
use Illuminate\Support\Facades\Auth;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class Authenticate extends Middleware
{
    /**
     * Get the path the user should be redirected to when they are not authenticated.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return string|null
     */
    protected function redirectTo($request)
    {
        if (! $request->expectsJson()) {
            return route('login');
        }
    }

    public function handle($request, Closure $next, ...$guards)
    {
        $menus = $this->menuTree();
        view()->share('menus', $menus);
        return parent::handle($request, $next, $guards); // TODO: Change the autogenerated stub
    }

    public function menuTree()
    {
        return Permissions::with('child_hasMany')
            ->where('is_menus', 1)
            ->where('pid', 0)
            ->where('guard_name', 'web')
            ->where('show', 1)
            ->get();
    }


}
